theme: jekyll-theme-cayman
title: PyTgCalls | Docs
description: Async client API for the Telegram Group Calls
image: https://user-images.githubusercontent.com/32808683/111091141-62473b00-8508-11eb-9c05-3e0fd4a21af3.png
logo: https://user-images.githubusercontent.com/32808683/111091141-62473b00-8508-11eb-9c05-3e0fd4a21af3.png